# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hive < Formula
  desc "CLI/TUI for managing multiple AI agent sessions in isolated git environments"
  homepage "https://github.com/colonyops/hive"
  version "0.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/colonyops/hive/releases/download/v0.31.0/hive_Darwin_x86_64.tar.gz"
      sha256 "ab1ad4ca22ede9454f841510645923ea36267abb3d6d6bc407643f53f6e00f76"

      def install
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/colonyops/hive/releases/download/v0.31.0/hive_Darwin_arm64.tar.gz"
      sha256 "cb43ced8023744c08519af90c1631abde935d1846d10cb27316e2880f07368e5"

      def install
        bin.install "hive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/colonyops/hive/releases/download/v0.31.0/hive_Linux_x86_64.tar.gz"
      sha256 "35ce6ce5f4496190b9c9f882d019891247e9a9bb9321a6921511033add832c7b"
      def install
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/colonyops/hive/releases/download/v0.31.0/hive_Linux_arm64.tar.gz"
      sha256 "0f93a5f49509415255a5f946580994d85104e07e7f1c1507ad7ca1b1cb579e61"
      def install
        bin.install "hive"
      end
    end
  end
end
