# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  version "0.49.1"

  on_macos do
    on_intel do
      sha256 "5cc12c35a6d0d09d5c217b89f524da5f07d4d097e1d358d267fa50af60458a99"
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a542c6c6be1024ce2009cd2e29ab162637f8c29a91cec6d79a0b970cf0dd310f"
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6bf87f08e2719a1329397eb159ea772bd8a539f330eb8bd66f2ce645647327d"
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6ee203703c46ec6ac68081dfea51d1eca6851e1a7d44a900ed622a7602bfb493"
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_arm64.tar.gz"
    end
  end

  name "hive"
  desc "CLI/TUI for managing multiple AI agent sessions in isolated git environments"
  homepage "https://github.com/colonyops/hive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hive"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This binary is not signed or notarized. The installer removes the macOS quarantine attribute automatically.

    Requires tmux and git to be installed.
  EOS
end
