# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  name "hive"
  desc "CLI/TUI for managing multiple AI agent sessions in isolated git environments"
  homepage "https://github.com/colonyops/hive"
  version "0.35.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hive"

  on_macos do
    on_intel do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_x86_64.tar.gz"
      sha256 "390e8ed3364c845a2d26630806b2a6d89162cfbceaad7c4649a52a4de578aca8"
    end
    on_arm do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_arm64.tar.gz"
      sha256 "589c4973bd67c9fcf5d7d6dbdc1fc351493dd2734f5dbd884549a6a384283d34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_x86_64.tar.gz"
      sha256 "1e15981085e27d77c530f16c9d6008dcc5386c45b1b298a989ea2e44a868ebe6"
    end
    on_arm do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_arm64.tar.gz"
      sha256 "493022bca2fae6ed4976f9db36e7b418f2d208b7a0c79eb0d7e9148ae8aba5e7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hive"]
    end
  end

  caveats do
    "This binary is not signed or notarized. The installer removes the macOS quarantine attribute automatically."
    ""
    "Requires tmux and git to be installed."
  end

  # No zap stanza required
end
