# This file was generated by GoReleaser. DO NOT EDIT.
cask "hive" do
  name "hive"
  desc "CLI/TUI for managing multiple AI agent sessions in isolated git environments"
  homepage "https://github.com/colonyops/hive"
  version "0.42.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hive"

  on_macos do
    on_intel do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_x86_64.tar.gz"
      sha256 "31ac44ba586c311fd4e627b2f53b72d71fc8ec97641d4efa843ff265c3d4514b"
    end
    on_arm do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Darwin_arm64.tar.gz"
      sha256 "d100b14c7dcf9591cd81c5b4ff49bae95117fa5b6440e030fc0583a7b78c02da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_x86_64.tar.gz"
      sha256 "df84e575a3f369d9429228ab55a113dcea501daf48b72d91f9efc67e5353bc72"
    end
    on_arm do
      url "https://github.com/colonyops/hive/releases/download/v#{version}/hive_Linux_arm64.tar.gz"
      sha256 "2df6b24647fb48fdc89c8719de4d45537fd921c98ae1bd6cc343d358fc49279c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hive"]
    end
  end

  caveats do
    "This binary is not signed or notarized. The installer removes the macOS quarantine attribute automatically."
    ""
    "Requires tmux and git to be installed."
  end

  # No zap stanza required
end
